# Generated by Django 3.0.5 on 2020-05-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='job',
            field=models.CharField(default='none', max_length=120),
        ),
    ]
