# Generated by Django 3.0.5 on 2020-05-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='client_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='manager_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
