# Generated by Django 3.0.5 on 2020-05-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200511_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
