# Generated by Django 3.0.5 on 2020-05-11 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_message_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='client_viewed',
            new_name='recipient_viewed',
        ),
        migrations.RemoveField(
            model_name='message',
            name='manager_viewed',
        ),
    ]
